# Generated by Django 4.0.4 on 2022-05-04 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.FileField(null=True, upload_to='images/profile/')),
                ('verification_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 4, 16, 56, 58, 208730))),
                ('updated_at', models.DateTimeField(null=True)),
                ('removed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_description', models.TextField(max_length=300)),
                ('slug', models.CharField(max_length=100)),
                ('category_id', models.BigIntegerField(null=True)),
                ('post_image', models.FileField(upload_to='', verbose_name='images/post/')),
                ('user_id', models.BigIntegerField(null=True)),
                ('post_status', models.CharField(max_length=100)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 4, 16, 56, 58, 210725))),
                ('updated_at', models.DateTimeField(null=True)),
                ('removed_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
